name: cache
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: zachcoyle
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#darwinConfigurations.Zacharys-MacBook-Pro.system --show-trace
      - run: nix build .#darwinConfigurations.Zachs-Macbook-Pro.system --show-trace
